### ISSUE TITLE
undefined is not an object (RNFSManager.readDir)

### ISSUE THREAD

**Issue by JonathanWi** [jayesbe/react-native-cacheable-image#1]
Hey!

Just installed your component but when trying to use it I'm prompted with this error message... Any idea?

The peerDependencies have been installed, and I'm running the app on an iPhone 6.

(side question: can this be used with Animated? Animated.CacheableImage)

Cheers!

**Comment by jayesbe** [comment]
The component at the moment uses Andriod Progress API.  It needs to have the ios progress integrated. Unfortunately I don't have a mac or any way of developing ios apps. PR's are welcome though.

**Comment by vitorhorta** [comment]
I solved it by following this installation guide:
https://github.com/johanneslumpe/react-native-fs#usage

**Comment by jayesbe** [comment]
@vitorhorta is this for iOS or Android ?

**Comment by vitorhorta** [comment]
It's for Android. I thought it should solve the issue for both Android and iOS as the error message is the same.

**Comment by pavlelekic** [comment]
@vitorhorta how did you make it run on ios? I installed the react-native-fs, linked it, then installed react-native-cacheable-image but I get an error. Here is the screenshot:
![simulator screen shot sep 5 2016 10 32 37](https://cloud.githubusercontent.com/assets/7754193/18241957/4940003a-7354-11e6-8f6d-b21e5ffef61b.png)

**Comment by jayesbe** [comment]
@pavlelekic  Unfortunately I cannot test with iOS.  The current version uses ProgressBarAndroid

https://github.com/jayesbe/react-native-cacheable-image/blob/master/image.js#L128

which is probably causing your issue.  It needs to be refactored out.  PR's are very welcome.

**Comment by scerelli** [comment]
@pavlelekic the bug it's fixed now. The problem was that you installed the new versions of `react-native-fs` that has several breaking changes. You can find the fixes to your issue inside my PR: https://github.com/jayesbe/react-native-cacheable-image/pull/6/commits/e86017ff12cb329cd58fd6e42fbf03c1559b849c#diff-a55ceb1e7b521b129b05093109b0da5bR60 .

**Comment by nancyhuynh** [comment]
@scerelli do you know the status of having your PR merged? I'm also running into the same "RNFSManager.readDir" error. Thanks!

**Comment by jayesbe** [comment]
```
                                                                                  Sorry! I will publish tonight. 
```

**Comment by scerelli** [comment]
@nancyhuynh To everyone: to get rid of these errors you have to link `react-native-fs` to your project. I already updated `react-native-cacheable-image` to match the new apis. But library linking is _mandatory_
