### ISSUE TITLE
Add react-native-fs to Readme

### ISSUE THREAD

**Issue by scerelli** [jayesbe/react-native-cacheable-image#10]
What i suggest is to add a explicit paragraph inside the Readme where we advise users thatif they don't linking `react-native-fs` to xcode and android project the component will not work

**Comment by jayesbe** [comment]
This is fair. I believe the command is 'rnpm link' ?

**Comment by scerelli** [comment]
I did it manually because for some reason rnpm link didn't work.

**Comment by jayesbe** [comment]
updated documentation for link
