### ISSUE TITLE
error: Cannot read property 'RNFSFileTypeRegular' of undefined

### ISSUE THREAD

**Issue by valinaga** [jayesbe/react-native-cacheable-image#12]
I got this when I try to use this component.

ExceptionsManager.js:62
Cannot read property 'RNFSFileTypeRegular' of undefined
Any idea on how to get it right?

**Comment by sand25** [comment]
You need to link module properly. Use rnpm link and then possibly on Android you need to instantiate java module inside getPackages method inside your main ReactApplication. It didn't do it automatically when I used it.

**Comment by jayesbe** [comment]
Hi @valinaga  try running 

rnpm link react-native-fs

make sure you have rnpm installed

npm install -g rnpm

**Comment by JClackett** [comment]
Hi @jayesbe,
I used rnpm link as described in the README but am still getting the same error?

**Comment by arnsa** [comment]
+1 same here. I did link the library, but I am still getting the same error on Android and iOS.
