### ISSUE TITLE
The callback downloadFile() exists in module RNFSManager

### ISSUE THREAD

**Issue by SunnyGurnani** [jayesbe/react-native-cacheable-image#14]
![image](https://cloud.githubusercontent.com/assets/943576/19408184/1f044f60-926c-11e6-9920-ac369c9667bc.png)

**Comment by jayesbe** [comment]
Hi @SunnyGurnani  did you run the link command ?  `react-native link react-native-fs` ?

**Comment by SunnyGurnani** [comment]
Yep I did

**Comment by jayesbe** [comment]
What version of ReactNative ?

**Comment by StanLee12** [comment]
I have this problem too,The version is 0.33.0

**Comment by jayesbe** [comment]
@YuiGakki @SunnyGurnani were you able to figure it out or still having issues?

**Comment by SunnyGurnani** [comment]
Sorry I stopped using this it may be to a React Native image Load issue going on on IOS.
Can you tell me how this library is differentiated from HTTP Cache which react-native already has ?

**Comment by jayesbe** [comment]
@SunnyGurnani I will have to look into the native HTTP Cache. Can you provide a link?

**Comment by hgoldwire** [comment]
I haven't found details, but the react native docs for Image say there's a cache.  I can't tell whether the cache is always populated, or only if you call the prefetch() method.   Take a look at https://facebook.github.io/react-native/docs/image.html prefetch method.

Separately I've read that Image uses fetch API which allegedly has a cache; I haven't seen evidence of that bc I get loading delays when loading the same Image in different components.
