### ISSUE TITLE
Getting "Possible Unhandled Promise Rejection warning" everytime I render image

### ISSUE THREAD

**Issue by schlaegerz** [jayesbe/react-native-cacheable-image#18]
Everything seems to work fine but I am get a whole lot of these warnings.

**Comment by jayesbe** [comment]
@schlaegerz can you check the latest version to see if you have the issue still.

**Comment by schlaegerz** [comment]
Works great! Thanks a lot for this package!

**Comment by jayesbe** [comment]
Awesome and thank you for using it.
