### ISSUE TITLE
A semicolon is required after a class property

### ISSUE THREAD

**Issue by spaceo** [jayesbe/react-native-cacheable-image#2]
I get this error in image.js:
Error while persisting cache: SyntaxError /home/mikkel/workspace/react/native-starter-pro/NativeStarter.git/node_modules/react-native-cacheable-image/image.js: A semicolon is required after a class property (11:9)
Guess it is because I am running my app in strict mode?
Would be nice to correct it anyway?

**Comment by jayesbe** [comment]
Is that the the line that defines the default state ? 

```
state: {
    ...
}
```

starting at line 11 ?

**Comment by spaceo** [comment]
yes

**Comment by jayesbe** [comment]
Does adding a semcolon fix the build ?  I can't test this at the moment and I don't have tests written that would make sure it does.

**Comment by spaceo** [comment]
Yes, the error goes away when I add the semicolon.

**Comment by spaceo** [comment]
Shall I make a PR?

**Comment by jayesbe** [comment]
please. thanks

**Comment by jayesbe** [comment]
merged https://github.com/jayesbe/react-native-cacheable-image/pull/3
