### ISSUE TITLE
Default image not showing up

### ISSUE THREAD

**Issue by schlaegerz** [jayesbe/react-native-cacheable-image#20]
This was a small issue, posting here in case anyone else runs into this. 

The default image wasn't showing up, to fix this I had to set the style.backgroundColor on the CacheableImage to transparent.

**Comment by jayesbe** [comment]
This tells me that backgroundColor should be transparent by default

**Comment by jayesbe** [comment]
Added transparency by default.

**Comment by jayesbe** [comment]
Added transparency by default.

**Comment by jayesbe** [comment]
Added transparency by default.

**Comment by jayesbe** [comment]
Added transparency by default.

**Comment by jayesbe** [comment]
Added transparency by default.
