### ISSUE TITLE
cacheable-image component shows Activity indicator that doesn't go away. 

### ISSUE THREAD

**Issue by Obsessive** [jayesbe/react-native-cacheable-image#21]
Constant Activity indicator that doesn't go away and the image doesn't load.
no errors thrown .

steps followed: 
- ```npm i react-native-cacheable-image --save```
- ```react-native link react-native-fs```
- ```react-native run-ios```
code: 
```
import CacheableImage from 'react-native-cacheable-image'
return(
<View>
 <CacheableImage
                            style={styles.thumbnail}
                            source={{uri: 'http://placeholdit.imgix.net/~text?txtsize=9&txt=30×30&w=30&h=30'}}
                            defaultSource={{uri: 'http://placeholdit.imgix.net/~text?txtsize=9&txt=30×30&w=30&h=30'}} />
</View>
)
```

project is generated using ignite 

```
Computer
  Platform: darwin

Ignite
  Version: 1.10.1
  Path: /usr/local/bin/ignite

Node
  Version: v6.5.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.3
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.33.1
```

**Comment by Obsessive** [comment]
any body else having inconsistent results? 
images not loading always?

**Comment by Obsessive** [comment]
If anyone is having similar issues with this component, please try out the fork available on my account.

**Comment by jayesbe** [comment]
@Obsessive Just pushed a new version.. can you give it a shot? 

Also an indefinite ActivityIndicator is a valid use case. Providing a bogus url or no internet connectivity without a cached image already available, or a default image available, the activityindicator would be indefinite.

**Comment by Obsessive** [comment]
Great ! This works way smooth now
