### ISSUE TITLE
setState warning

### ISSUE THREAD

**Issue by sjgtongji** [jayesbe/react-native-cacheable-image#22]
the component functions well but in debug mode, there is a warning:

setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the CacheableImage component.

**Comment by jayesbe** [comment]
@sjgtongji What platform, ios or android?  

I don't see this happening.. can you post your reference implementation?

**Comment by sjgtongji** [comment]
on android platform 

```
                   import CacheableImage from 'react-native-cacheable-image';

                  <View style={styles.rowDown}>
                          <CacheableImage
                                 style={styles.teamImg}
                                 source={{uri:rowData.HomeTeamIcon}}
                                     defaultSource={{uri : defaultHome , width : 80 , height : 80}}/>
                  </View>
```

above is my code

**Comment by jarretmoses** [comment]
+1 having a similar issue on ios this is my component (working on android).
`<View style={wrapperStyles}>
      <CacheableImage
      source={{uri: props.url}}
      style={imageStyles}
    />
</View>`

**Comment by jayesbe** [comment]
I have been researching this issue. I can't seem to replicate this on android at all.  There are others having the same issue though and quite a few show up just googling. 

The only thing I can think of is that the component begins to unmount even before its mounted. However.. you can setState when mounting. setState should most definitely work during a componentWillMount(). 

PR #25 doesn't make sense to me.. its an anti-pattern to have an isMounted value.. should not be required. 

Does this only happen occasionally? is there a change of sorts happening to the component even before it has a chance to mount?

**Comment by jayesbe** [comment]
Can you guys post the stack trace? or point to the exact line in image.js causing the issue ?

**Comment by nbolender** [comment]
@jayesbe It looks like this warning is only caused within NetInfo.isConnected.fetch().then(). What happens is the component renders defaultSource, which is of course another CacheableImage component. This component then unmounts before the NetInfo promise is resolved.

It seems that the NetInfo event handler is called with the intial status anyway, so we may be able to get away with just removing the NetInfo.isConnected.fetch() statement.

Another thing to think about is local images don't need to utilize NetInfo at all. Not sure if that is even worth worrying about, though.

**Comment by jayesbe** [comment]
Would a .catch() help after the .then() ?

**Comment by jayesbe** [comment]
@nbolender can you try replacing the componentWillMount() with 


    componentWillMount() {

        NetInfo.isConnected.addEventListener('change', this._handleConnectivityChange);
        
        this._processSource(this.props.source);
    }

    componentDidMount() {
        // initial
        NetInfo.isConnected.fetch().done(this._handleConnectivityChange);    
    }

**Comment by nbolender** [comment]
@jayesbe Catch didn't work; the setState warning doesn't throw an error.

Moving the fetch to componentDidMount didn't work either.

Ideally we could cancel the promise, but the built-in promises don't support that.

**Comment by jayesbe** [comment]
Interesting. I do have the networkAvailable defaulted to false.  It wont get set to true unless a call is made.

Im assuming its a long shot but add the fetch to the constructor?


    constructor(props) {
        super(props)
        this.imageDownloadBegin = this.imageDownloadBegin.bind(this);
        this.imageDownloadProgress = this.imageDownloadProgress.bind(this);
        this._handleConnectivityChange = this._handleConnectivityChange.bind(this);
        
        this.state = {
            isRemote: false,
            cachedImagePath: null,
            downloading: false,
            cacheable: true,
            jobId: null,
            networkAvailable: false
        };
        
        NetInfo.isConnected.fetch().done(this._handleConnectivityChange);   
    };

checking now.

**Comment by jayesbe** [comment]
Even in the constructor it works for me.. on android. I have a really simple test though.. two CacheableImage components one nested inside the other. But you said this is a defaultSource issue.  Let me try with that.

**Comment by jayesbe** [comment]
ok definitely a defaultSource issue. This component is in the middle of being mounted when its unmounted during another render

**Comment by nbolender** [comment]
Would it be worth avoiding by rendering a ResponsiveImage instead of CacheableImage for defaultSource? It's sort of side-stepping the problem.

**Comment by jayesbe** [comment]
Im thinking we should add a prop. checkNetwork .. if true it makes the NetInfo fetch call.. if false it doesnt.  It should default to true.

Then in the renderDefaultSource we should pass in the inverse of networkAvailable.  If networkAvailable is true.. checkNetwork on the defaultSource CacheableImage should be false. 

something like ...ie

    renderDefaultSource() {
        const { children, defaultSource, ...props } = this.props;
        return (
            <CacheableImage {...props} source={defaultSource} checkNetwork={{!this.state.networkAvailable}}>
            {children}
            </CacheableImage>
        );
    }

not sure if this will work havent tested.. but can get to it in the morning.. what do you think?

**Comment by nbolender** [comment]
Well, you really only need to check the network in the root component, since a change in network availability would cause a re-render of the default source anyway. If you could get the child component in renderDefaultSource() to *not* check the network and instead use the networkAvailable prop of its parent, I think you'd be good.

Of course you will still have an issue if the root component is mounted and unmounted quickly, but that might be best left to a FAQ in the documentation.

**Comment by jayesbe** [comment]
Yes exactly. Will try and resolve this by tomorrow.

**Comment by jayesbe** [comment]
@nbolender Have to head out but made a quick patch.. if you have time to check let me know if its good?  otherwise I will look into it further tomorrow.  Thanks for the help. 

```
diff --git a/image.js b/image.js
index c53e479..ea6c72b 100644
--- a/image.js
+++ b/image.js
@@ -21,8 +21,8 @@
             downloading: false,
             cacheable: true,
             jobId: null,
-            networkAvailable: false
-        };
+            networkAvailable: props.networkAvailable
+        };  
     };
 
     componentWillReceiveProps(nextProps) {
@@ -156,14 +156,14 @@
 
     componentWillMount() {
         NetInfo.isConnected.addEventListener('change', this._handleConnectivityChange);
-        // initial
-        NetInfo.isConnected.fetch().then(isConnected => {
-            this.setState({networkAvailable: isConnected});
-		});
+        
+        if (this.props.checkNetwork) {
+            NetInfo.isConnected.fetch().done(this._handleConnectivityChange);
+        }
         
         this._processSource(this.props.source);
     }
-
+    
     componentWillUnmount() {
         NetInfo.isConnected.removeEventListener('change', this._handleConnectivityChange);
     
@@ -215,9 +215,10 @@
     }
 
     renderDefaultSource() {
-        const { children, defaultSource, ...props } = this.props;
+        const { children, defaultSource, checkNetwork, ...props } = this.props;
+        const { networkAvailable } = this.state;
         return (
-            <CacheableImage {...props} source={defaultSource}>
+            <CacheableImage {...props} source={defaultSource} checkNetwork={false} networkAvailable={networkAvailable} >
             {children}
             </CacheableImage>
         );
@@ -230,7 +231,9 @@
     useQueryParamsInCacheKey: React.PropTypes.oneOfType([
         React.PropTypes.bool,
         React.PropTypes.array
-    ])
+    ]),
+    checkNetwork: React.PropTypes.bool,
+    networkAvailable: React.PropTypes.bool
 };
 
 
@@ -239,5 +242,7 @@
     activityIndicatorProps: {
         style: { backgroundColor: 'transparent', flex: 1 }
     },
-    useQueryParamsInCacheKey: false // bc
+    useQueryParamsInCacheKey: false, // bc
+    checkNetwork: true,
+    networkAvailable: false
 };
\ No newline at end of file

```

**Comment by nbolender** [comment]
@jayesbe Seems to work for me, although I had to add checkNetwork={false} wherever I was using a static source. Checking to see if the source is local or not first would solve that, but then again I could be using ResponsiveImage directly.

**Comment by jose920405** [comment]
+1 same warning in ios

**Comment by jayesbe** [comment]
The setState warning can still happen at any moment if component is removed from the view. There is not much we can do to prevent it but be vigilant with updating the rendering based on changes to state and props. Thanks to @nbolender and some additional changes I believe setState warnings have been minimised but they can still happen depending on the use case.

**Comment by techrah** [comment]
This prevents `setState` from being called on an unmounted component when using the `defaultSource` property.

```
    constructor(props) {
        super(props)
        ...
        this.abort = false;
    };

    async checkImageCache(imageUri, cachePath, cacheKey) {
        const dirPath = DocumentDirectoryPath+'/'+cachePath;
        const filePath = dirPath+'/'+cacheKey;

        RNFS
        .stat(filePath)
        .then((res) => {
            if (res.isFile() && res.size > 0) {
                // It's possible the component has already unmounted before setState could be called.
                // It happens when the defaultSource and source have both been cached.
                // An attempt is made to display the default however it's instantly removed since source is available

                // means file exists, ie, cache-hit
                !this.abort && this.setState({cacheable: true, cachedImagePath: filePath});
            }
            ...
    }

    componentWillUnmount() {
        this.abort = true;
        ...
    }
```
