### ISSUE TITLE
RNFSManager.stat got 1 arguments, expected 2 

### ISSUE THREAD

**Issue by ranjithnori** [jayesbe/react-native-cacheable-image#30]
Hi, Thanks for writing this module. I'm having some trouble using it though. I get the above mentioned error. This seems to be linked to react-native-fs. So, I have double checked if the linking of react-native-fs is done properly, but couldn't get it to work.

Any pointers ?

**Comment by Suresh-R-S** [comment]
Hi I'am facing similar issue. What did you do to overcome it?
I have linked react-native-fs properly.

The following is the error that I'am facing:
"RNFSManager. was called with 1 arguments, but expects 2. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away."
