### ISSUE TITLE
undefined is not an object(evaluating 'RNFSManager.RNFSFileTypeRegular')

### ISSUE THREAD

**Issue by yhq634** [jayesbe/react-native-cacheable-image#31]

**Comment by nbolender** [comment]
Make sure you have properly linked react-native-fs

**Comment by yhq634** [comment]
I have make sure that

**Comment by smkhalsa** [comment]
I'm also getting this issue

**Comment by jose920405** [comment]
+1

**Comment by shrutic** [comment]
+1 on ios

**Comment by SunShinewyf** [comment]
me too, any way to solve it?

**Comment by ghost** [comment]
https://github.com/johanneslumpe/react-native-fs

I had to follow "Make alterations to the following files" below _Usage (Android)_ in addition to linking it.

**Comment by clarkie** [comment]
Something that caught me out (iOS newbie!) was that you have to rebuild the app after linking. 

How I miss the web! 😄

**Comment by asimolmez** [comment]
+1 iOS

**Comment by jayesbe** [comment]
This is pretty much an issue with the RNFS not being properly linked.

**Comment by jcady** [comment]
My issue was not properly installing all the dependencies, linking react-native-fs, and rebuilding the app:
```
npm install --save react-native-cache-image react-native-fs url-parse crypto-js
react-native link react-native-fs
react-native run-ios
```

**Comment by mateodelnorte** [comment]
I'm getting the same issue. After running `react-native link` and linking all modules, I get a C++ build error: 
```
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/mateodelnorte/development/my-project/ios/build/Build/Intermediates/TcpSockets.build/Debug-iphonesimulator/TcpSockets.build/Objects-normal/x86_64/TcpSockets.o TcpSockets.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
Any ideas?

**Comment by Stophface** [comment]
@mateodelnorte if you build the code in `xCode`, the error message you get is more detailed.

**Comment by hash9** [comment]
Steps to fix:
1: Follow all the 'Usage Steps' as described in the [react-native-fs](https://github.com/itinance/react-native-fs)
2: If the issue still persists, do _react-native start --reset-cache_ inside terminal OR _react-native run-android/ios_  if the app is not installed, depending on whichever OS you want to run.
Hope it solves 👍

**Comment by rajat-np** [comment]
This worked for me (using a physical device) :
1: Follow all the 'Usage Steps' as described in the react-native-fs.
2.Then uninstall the app from the device and reinstall it.

**Comment by kaxline** [comment]
Since the Usuage Steps make it sound like you could do one of the three options for iOS (Adding automatically, adding with Cocoapods, adding manually), I started debugging problems with using the first two instead of trying all three. Finally I tried the manual setup and that worked when nothing else did.

**Comment by patrickLorenz83** [comment]
I have the same problem with expo, any solutions when I'm using expo?

**Comment by ThinhNguyenVN** [comment]
In my case, follow code :
			<CacheableImage
                            style={{ width, height }}
                            source={{ uri }}
                            checkNetwork
                            networkAvailable
                        />
It was fixed. Hope that can help u

**Comment by devsteppe9** [comment]
In Android after linking auto I entered MainApplication.java below and it worked for me
`import com.rnfs.RNFSPackage; // <------- add package 
 
public class MainApplication extends Application implements ReactApplication {
   // ... 
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(), // <---- add comma 
        new RNFSPackage() // <---------- add package 
      );
    }`
