### ISSUE TITLE
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState ...

### ISSUE THREAD

**Issue by panhna** [jayesbe/react-native-cacheable-image#57]
I user the flatlist to load the video list. it ok for the first time. but until i try pull-to-refresh to reload the list again. it start show the warning message. and it the same warning keep increase when i try to scroll the list.

    "react": "16.0.0-alpha.3",
    "react-native": "0.43.2",
    "react-native-cacheable-image": "^1.5.1",

![simulator screen shot jun 17 2017 9 14 43 pm](https://user-images.githubusercontent.com/5246440/27253705-7c3ddb4e-53a3-11e7-8127-6ce513ebc619.png)
![simulator screen shot jun 17 2017 9 19 40 pm](https://user-images.githubusercontent.com/5246440/27253706-7f94b150-53a3-11e7-9d5a-4976a96d687d.png)

Any idea with this warning message? Thx

**Comment by BeckhamVinoth** [comment]
Me too got same error . did  anyone solved this kinda error before ? please some one help me out from this . Am using react-native

**Comment by jayesbe** [comment]
May be related to the default, really depends on your code as well. However, this module is pretty much deprecated now, RN now provides an ImageStore API that handles caching, its more robust and can be used in conjunction with Image. CacheableImage is no longer necessary.
