### ISSUE TITLE
Release "dev" branch to NPM?

### ISSUE THREAD

**Issue by blake-simpson** [jayesbe/react-native-cacheable-image#63]
Hi, I was wondering if it would be possible to merge the `dev` branch to `master` and release that to NPM? Or is there anything still needing done in the branch before it is merged that we can help with? 

My problem is the `dev` branch has the required fixes for prop-types being moved to it's own package and currently we are having trouble updating a RN project because the NPM version of cacheable image still references `React.PropTypes` which is no longer available in React 16.

**Comment by jayesbe** [comment]
Ill get this merged over to master this weekend.

**Comment by eseQ** [comment]
Hello. What about update?

**Comment by jayesbe** [comment]
merged to master and published

**Comment by eseQ** [comment]
@jayesbe thank you.
