### ISSUE TITLE
Undefined is not an object when import cacheable-image

### ISSUE THREAD

**Issue by MERTKIRKALI** [jayesbe/react-native-cacheable-image#65]
version: "react-native": "^0.54.0",
i alread installed all dependecy, and link react-native-fs and rebuild my project.

when i run npm ls command it will give me this,

```
npm ERR! peer dep missing: react@^16.3.0-alpha.1, required by react-native@0.54.0
npm ERR! peer dep missing: react-native@^0.51.0, required by react-native-fs@2.9.11
npm ERR! peer dep missing: react-native@^0.51.0, required by react-native-fs@2.9.11

```
When i add just this line 
`import CacheableImage from 'react-native-cacheable-image';`

i have this error

![e3109bc8-4a44-4052-97d8-1e8b555f434c](https://user-images.githubusercontent.com/11061078/37058036-4ac55040-219a-11e8-8ec8-6640a66a787b.jpg)

image.js does not have `import PropTypes from 'prop-types';` is this be a problem ? or react-native-fs want react-native version 0.51 ?

Does anyone can work with react native 0.54 ?

**Comment by LorandP** [comment]
This happened to me as well....

**Comment by nic-thomson** [comment]
the fix is here 
the fix is here in 
https://github.com/jayesbe/react-native-cacheable-image/pull/61/commits/946531f6fba9c377be6dfcbfd1eaeb1edf621363
