### ISSUE TITLE
Usage of NetInfo through react-native

### ISSUE THREAD

**Issue by rasmniel** [jayesbe/react-native-cacheable-image#69]
Given the `react-native-netinfo` repository has been created to modularize dependencies of React Native, I think `react-native-cacheable-image` should comply with this modularization by including the new NetInfo repository as a dependency. Better sooner than later ;)

Furthermore, this alleviates the annoyance of having to mute the warning produced by React Native in newer versions (I'm unsure at which version RN starts printing this warning):
>Warning: NetInfo has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/netinfo' instead of 'react-native'. See https://github.com/react-native-community/react-native-netinfo

**Comment by jayesbe** [comment]
Fixed with latest merge
