### ISSUE TITLE
Can't we use ProgressViewIOS instead of ProgressBarAndroid?

### ISSUE THREAD

**Issue by scerelli** [jayesbe/react-native-cacheable-image#7]
I saw that you using a progress bar for android and none for IOS. What do you think if we use this for ios:
https://facebook.github.io/react-native/docs/progressviewios.html

so we will support both Platforms

**Comment by jayesbe** [comment]
Yes most definitely. I had no way to test iOS so I chose not to implement it. If you can add it in that would be very much appreciated. 

Originally I thought maybe create imageProgress.android.js and imageProgress.ios.js and put the specific progress loaders in respective files. Then import ImageProgress element.  But I am open to any decent working implementation.

**Comment by scerelli** [comment]
Ok give me some time. I think tomorrow i can fix it

**Comment by jayesbe** [comment]
Take your time :)  and thanks for the help.

**Comment by jayesbe** [comment]
@scerelli merged in @fluciotto PR that changes the ProgressView to ActivityIndicator
